### ISSUE TITLE
Link doesn't show up

### ISSUE THREAD

**Issue by SeBlll** [mrmadbhai/MadCam#2]
For some reason, it didn't show the link. Please help

**Comment by republic101** [comment]
yes same problem

**Comment by pourgholamreza** [comment]
HI, i turn on hotspot and use mobile DATA but direct link didnot show me any link

**Comment by JohnThomson555** [comment]
Madcam is not working properly. Untill author fixes it, you can try similar tool [CamHacker](https://github.com/KasRoudra/CamHacker)

**Comment by Anoymouss** [comment]
> Madcam is not working properly. Untill author fixes it, you can try similar tool [CamHacker](https://github.com/KasRoudra/CamHacker)

Bro but how do I open camhacker picture

**Comment by abhi783** [comment]
If ngrock not works then go with servo

**Comment by mrmadbhai** [comment]
check updated tool
